language: go
go:
  - 1.9
before_install:
  - go get -t -v ./...
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
script:
  - goveralls -v -race -service=travis-ci
notifications:
  email:
    recipients:
      - alastairruhm@gmail.com
  slack: 'alastairruhm:AN7iL7hiZhXMjin6eWowNSax'
